### ISSUE TITLE
.envrc no longer created on init, docs inaccurate

### ISSUE THREAD

**Issue by bketelsen** [jetpack-io/devbox#1078] opened 2023-06-01 13:59 UTC
**Current Behavior (bug)**
`devbox init` doesn't create an `.envrc` file when the direnv binary is installed. 

**Expected Behavior (fix)**
`devbox init` should create an `.envrc` file when the direnv binary is installed. 

** Workaround **
`devbox generate direnv --force`

**Additional context**
```
Version:     0.5.3
Platform:    linux_amd64
Commit:      2ffe94fd2c71ad607c3f002d50fbe867002c4468
Commit Time: 2023-05-30T21:36:27Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

devbox.json:
```
{
  "packages": [
    "nodejs@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

**Comment by tebuevd** [comment] 2023-06-01 15:21
+1 Just spend a bunch of time installing direnv via various package managers to the same effect. The workaround works. Thank you @bketelsen

**Comment by mohsenari** [comment] 2023-06-01 17:27
@bketelsen Apologies for the miscommunication there. This is by design. We removed the auto-adding the `.envrc` if direnv is installed since it was a bit invasive. Instead, we removed the prompt we had for direnv and automatically run `direnv allow` when you run `devbox generate direnv`.

**Comment by bketelsen** [comment] 2023-06-01 17:30
No worries. I'll change the title of the issue to a docs bug report

**Comment by bketelsen** [comment] 2023-06-01 17:30
relevant docs link:
https://www.jetpack.io/devbox/docs/ide_configuration/direnv/

**Comment by Lagoja** [comment] 2023-06-02 23:15
Docs changes have been merged

**Closed by Lagoja** 2023-06-02 23:15 UTC
Labels: bug
