### ISSUE TITLE
[Bug]: devbox won't remove packages that aren't declared in devbox.json

### ISSUE THREAD

**Issue by dnkmmr69420** [jetpack-io/devbox#1185] opened 2023-06-20 21:56 UTC
**Current Behavior (bug)**
When you remove packages from `devbox.json` the packages are removed from the flake and lock files but still exist in the nix profile

**Expected Behavior (fix)**
When I remove a package from `devbox.json` by editing the config, the next time I run either `devbox install` or `devbox update` the package should be automatically removed. So devbox should be removing any packages that aren't declared in `devbox.json`

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

```
Version:     0.5.5
Platform:    linux_amd64
Commit:      891e8de7a8ab7a3fec42fad069326d68cb84603e
Commit Time: 2023-06-19T19:18:00Z
Go Version:  go1.20.5
Launcher:    0.2.0
```

```json
{
  "packages": [
    
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

devbox won't automatically remove these

`devboxdir/.devbox/nix/profile/default/bin`

```
canberra-gtk-play@  es2gears@  glxinfo@  librewolf@  lzdiff@   lzgrep@  lzmadec@   neofetch@  unlzma@  xzcat@  xzdiff@   xzgrep@
chkstow@            es2_info@  kitten@   lzcat@      lzegrep@  lzless@  lzmainfo@  pfetch@    unxz@    xzcmp@  xzegrep@  xzless@
eglinfo@            glxgears@  kitty@    lzcmp@      lzfgrep@  lzma@    lzmore@    stow@      xz@      xzdec@  xzfgrep@  xzmore@
```

**Comment by savil** [comment] 2023-06-20 23:07
Thanks for filing the issue.

@ipince looks like #1181 would fix this issue. Could you confirm please?

**Comment by ipince** [comment] 2023-06-20 23:13
Yes, #1181 is a fix.

I'll close this as a duplicate of #1138, but thanks for the detailed bug report!

**Closed by ipince** 2023-06-20 23:13 UTC
Labels: bug
