### ISSUE TITLE
[Bug]: ImportError with version `GLIBC_ABI_DT_RELR' not found

### ISSUE THREAD

**Issue by sridharraman** [jetpack-io/devbox#1379] opened 2023-08-16 10:00 UTC
**Current Behavior (bug)**
I have a Django + PostgreSQL application and I get the following error when I try to run the migrations. The command `python3 manage.py makemigrations` gives this error:
```
import psycopg2 as Database
  File "/home/sridhar/django_app/.devbox/virtenv/python37Packages.pip/.venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libresolv.so.2)
```

**Expected Behavior (fix)**
The table has been created using `createdb`, so the migrations need to run.

**Additional context**
This is the devbox version:
```
Version:     0.5.11
Platform:    linux_amd64
Commit:      1052c4e37c16ce0df5d60afb8c82076cd290eee8
Commit Time: 2023-08-10T23:32:09Z
Go Version:  go1.20.7
Launcher:    0.2.0
```

This is the devbox.json file:
```
{
  "packages": [
    "python@3.7",
    "python37Packages.pip@latest",
    "openssl@latest",
    "postgresql@latest",
    "glibcLocales@latest"
  ],
  "shell": {
    "init_hook": [
      ". $VENV_DIR/bin/activate",
      "pip install -r requirements.txt --use-pep517"
    ]
  }
}
```

**Comment by savil** [comment] 2023-08-21 21:51
@sridharraman Thanks for filing this issue. This is a class of issue we're aware of and are hoping to have a solution for, but it'll take some time.

I think (not 100% sure) the cause of the issue tends to be that `pip` is expecting a different version of GLIBC than the nix standard-environment, or the `glibcLocales` is providing.

One ugly way to fix this would be to try to match the nixpkgs commit hashes in the `devbox.lock` for the `python37Packages.pip` and `glibcLocales`. This is obviously not ideal, but a workaround until we implement a more reliable fix. Does this work for you?

Also, could you share your `devbox.lock` file so I can try to repro?

**Comment by savil** [comment] 2023-08-22 00:34
Okay, I can repro. 

Branch: [savil/django-glibc-issue-1379](https://github.com/jetpack-io/devbox/compare/savil/django-glibc-issue-1379)
Commit: https://github.com/jetpack-io/devbox/commit/72543355f2a546d0653cc704e3091319d9dbad0d 
Steps:
`docker build -t <tag> Dockerfile`
`docker run -it <tag>`
inside container: `devbox run test`

**Comment by savil** [comment] 2023-08-22 04:44
I was unable to get a quick workaround fix working. I'll circle back tomorrow...

**Comment by savil** [comment] 2023-08-22 19:57
To unblock, the workaround would be to pin all the packages to `80c24eeb9ff46aa99617844d0c4168659e35175f` nixpkgs commit hash in the `devbox.lock`.

More granularly:
1. It seems that `python@3.7` and `postgres` need to be on the same nixpkgs commit hash to use the same glibc.
2. Devbox's implementation currently picks the stdenv from the first package-dependency. This is obviously not very intentional, and we could do better here.

**Comment by sridharraman** [comment] 2023-08-23 06:00
@savil this is my devjson.lock file.

```
{
  "lockfile_version": "1",
  "packages": {
    "glibcLocales@latest": {
      "last_modified": "2023-06-30T04:44:22Z",
      "resolved": "github:NixOS/nixpkgs/3c614fbc76fc152f3e1bc4b2263da6d90adf80fb#glibcLocales",
      "source": "devbox-search",
      "version": "2.37-8"
    },
    "glibcLocalesUtf8@latest": {
      "last_modified": "2023-06-30T04:44:22Z",
      "resolved": "github:NixOS/nixpkgs/3c614fbc76fc152f3e1bc4b2263da6d90adf80fb#glibcLocalesUtf8",
      "source": "devbox-search",
      "version": "2.37-8"
    },
    "openssl@latest": {
      "last_modified": "2023-07-23T03:35:12Z",
      "resolved": "github:NixOS/nixpkgs/af8cd5ded7735ca1df1a1174864daab75feeb64a#openssl",
      "source": "devbox-search",
      "version": "3.0.9"
    },
    "postgresql@latest": {
      "last_modified": "2023-06-30T04:44:22Z",
      "plugin_version": "0.0.2",
      "resolved": "github:NixOS/nixpkgs/3c614fbc76fc152f3e1bc4b2263da6d90adf80fb#postgresql",
      "source": "devbox-search",
      "version": "14.8"
    },
    "python37Packages.pip@latest": {
      "last_modified": "2021-02-27T20:39:16Z",
      "plugin_version": "0.0.1",
      "resolved": "github:NixOS/nixpkgs/5df05c902cde398e056eb6271d5fe13e418db4c6#python37Packages.pip",
      "source": "devbox-search",
      "version": "20.3"
    },
    "python@3.7": {
      "last_modified": "2023-01-02T04:31:48Z",
      "plugin_version": "0.0.1",
      "resolved": "github:NixOS/nixpkgs/a4379d2b0deefedc8dba360897557707ea9ee9a7#python37",
      "source": "devbox-search",
      "version": "3.7.16"
    }
  }
}
```

So, how do I pin the nixpkgs hash? If I use the one for postgres (`3c614fbc76fc152f3e1bc4b2263da6d90adf80fb`) for the python ones as well and do a `devbox build`, that will work?

**Comment by savil** [comment] 2023-08-23 22:30
@sridharraman here's a commit for the change I made to have all the packages use the same nixpkgs commit hash in the "resolved" field in `devbox.lock`: https://github.com/jetpack-io/devbox/commit/ec1ac43b143be3ecb644f968f1bf22d78a528fae

Does this work for you?

Note:
1. this is a really ugly workaround, but may help unblock you.
2. The other packages like openssl and postgresql will have slightly older versions than `@latest`.

We're still investigating a "proper" fix.

**Comment by sridharraman** [comment] 2023-08-31 06:04
@savil how do I pin the nixpkgs hash?

**Comment by savil** [comment] 2023-08-31 17:53
@sridharraman this doc explains how to do that https://www.jetpack.io/devbox/docs/guides/pinning_packages/#manually-pinning-a-nixpkg-commit-for-a-package

something like:
```
> cat devbox.json
{
  "packages": [
    "github:NixOS/nixpkgs/80c24eeb9ff46aa99617844d0c4168659e35175f#openssl",
    "github:NixOS/nixpkgs/80c24eeb9ff46aa99617844d0c4168659e35175f#postgresql",
    "github:NixOS/nixpkgs/80c24eeb9ff46aa99617844d0c4168659e35175f#python37",
    "github:NixOS/nixpkgs/80c24eeb9ff46aa99617844d0c4168659e35175f#python37Packages.pip"
  ],
```

and then do `devbox install` or `devbox shell`. These will update your lock file too.

**Comment by savil** [comment] 2023-11-02 12:55
#1574 implements a product fix for this.

**Closed by savil** 2023-11-02 12:55 UTC
Labels: bug
