### ISSUE TITLE
mktemp: too few X's in template ‘devbox

### ISSUE THREAD

**Issue by gutenye** [jetpack-io/devbox#3] opened 2022-08-26 01:16 UTC
Steps to reproduce on macOS
 
 ```
$ curl -fsSL https://get.jetpack.io/devbox | bash
$ devbox init                                                                                                                           
mktemp: too few X's in template ‘devbox’
→ Downloading version 0.0.2...
✘ Command failed (exit code 23): curl --fail --silent --location --output /devbox_0.0.2_darwin_arm64.tar.gz https://github.com/jetpack-io/devbox/releases/download/0.0.2/devbox_0.0.2_darwin_arm64.tar.gz
```

**Comment by loreto** [comment] 2022-08-26 01:23
@gutenye Thanks for reporting ... which version of MacOS are you running so I can try to reproduce?

**Comment by gutenye** [comment] 2022-08-26 01:25
macOS Monterey 12.3.1

**Comment by NicGrimpe** [comment] 2022-08-26 01:26
I have the same issue running linux. (5.19.3-arch1-1)

**Comment by NicGrimpe** [comment] 2022-08-26 01:28
It's a little different actually
> devbox init
/usr/local/bin/devbox: line 225: arch: readonly variable
mktemp: too few X's in template ‘devbox’
→ Downloading version 0.0.2...
✘ Command failed (exit code 22): curl --fail --silent --location --output /devbox_0.0.2_linux_.tar.gz https://github.com/jetpack-io/devbox/releases/download/0.0.2/devbox_0.0.2_linux_.tar.gz

**Comment by loreto** [comment] 2022-08-26 01:59
@gutenye @NicGrimpe I believe this should be fixed now. Could you try re-installing with:

```
curl -fsSL https://get.jetpack.io/devbox | bash
```

And seeing if it works now?

**Comment by NicGrimpe** [comment] 2022-08-26 02:34
It now works for me! :rocket:

**Closed** 2022-08-26 02:51 UTC
Labels: bug
