### ISSUE TITLE
Proposal: add direnv config

### ISSUE THREAD

**Issue by pomdtr** [jetpack-io/devbox#209] opened 2022-10-05 23:02 UTC
Here is what I came up with:

```bash
#!/usr/bin/env bash

direnv_load devbox shell -- direnv dump
watch_file devbox.json
```

Thanks to this, as soon as I cd inside my project folder, I'm inside the devbox shell. Newly added package are also automatically loaded in the current shell.

It might be worth to add it somewhere, but I'm not sure where.

**Comment by pomdtr** [comment] 2022-10-07 10:07
Sadly it is not working really well in vscode (the direnv extension is not really good at overriding the user path). I think writing  a devcontainer instead would be better :)

**Comment by mohsenari** [comment] 2022-10-07 23:24
@pomdtr That's a great suggestion. We've been looking into integrating with `direnv` for the past couple weeks. You suggestion technically works but it also makes `devbox` think it's in a shell subprocess. So if you go into your direnv allowed directory and run `devbox shell` it will output:
>Error: You are already in an active devbox shell.
Run 'exit' before calling devbox shell again. Shell inception is not supported 
and when you run `exit` you're thrown out of your terminal, not the devbox shell subprocess which is not the intended behavior and can be confusing to some users.

This can be fixed, of course, but for the time being we're working on #213 which you put `devbox shell --print-env` in your `.envrc` and it updates your PATH with all the binaries you would get if you had been in a devbox shell.
We're also working on improving this command to make your shell's environment as close to a devbox shell environment as possible while making sure the confusions like the error above doesn't happen.

**Comment by mohsenari** [comment] 2022-10-07 23:29
@methyl We're looking into VSCode integration with `direnv + devbox` as well. If we can't get the extension to work with a devbox environment as we intend, we might have to write our own extension.
Either way, we'll follow up on this issue once we have a solid solution for VSCode setup.

**Comment by pomdtr** [comment] 2022-10-08 08:13
For direnv to work with vscode, it looks like you will need to patch the whole `code` process. See https://rastertail.net/blog/hacking-vscode/ for more details.

**Comment by mohsenari** [comment] 2022-10-21 20:14
@methyl We published a [devbox extension for VSCode](https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox&ssr=false#overview). It detects if you have devbox.json and when you open terminal in the IDE, it automatically goes to devbox shell.
Feel free to give it a try and let us know if you have any suggestions.

**Comment by methyl** [comment] 2022-10-24 10:30
@mohsenari thanks for a heads up! I think it's solving less problematic issue of having terminals in vscode open devbox shell, what's more important I think is to make sure extensions can use devbox to run the binaries.

**Comment by Lagoja** [comment] 2023-02-10 00:07
Closing this since we can now generate a `.envrc` file for Devbox. There's a second issue in here around better VSCode integration, which I will file as a separate issue.

**Closed by Lagoja** 2023-02-10 00:07 UTC
Labels: docs, feature
