### ISSUE TITLE
Can't install php81Extensions.blackfire

### ISSUE THREAD

**Issue by calvinbaart** [jetpack-io/devbox#386] opened 2022-12-16 08:25 UTC
I'm trying to add the blackfire extension to my devbox.json. After looking through NixOS search it seems the correct
package name should be ``php81Extensions.blackfire`` for PHP 8.1.

Adding it to my devbox.json:

```json
{
  "packages": [
    "php81",
    "php81Extensions.blackfire"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "52e3e80afff4b16ccb7c52e9f0f5220552f03d04"
  }
}
```

results in the following error:

```
Installing nix packages. This may take a while...
Error: apply Nix derivation: running command /nix/var/nix/profiles/default/bin/nix-env --profile /Users/calvinbaart/dev/devbox_test/.devbox/nix/profile/default --install -f /Users/calvinbaart/dev/devbox_test/.devbox/gen/development.nix: exit status 1 with command output: replacing old 'devbox-development'
installing 'devbox-development'
error: attribute 'extensionName' missing

       at /nix/store/j5a7i3dvxslg2ychfy53wdhg1m3xfrwm-source/pkgs/development/interpreters/php/generic.nix:94:29:

           93|
           94|           getExtName = ext: ext.extensionName;
             |                             ^
           95|
(use '--show-trace' to show detailed location information)
```

It should be noted that other extensions work perfectly (for example the imagick extension from the other issue)

The generated development.nix is this:

```nix
let
  pkgs = import (fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/52e3e80afff4b16ccb7c52e9f0f5220552f03d04.tar.gz";
  }) {
  };
    php81 = pkgs.php81.withExtensions ({ enabled, all }: enabled ++ (with all; [ blackfire ]));
  in with pkgs;
buildEnv {
  ignoreCollisions = true;
  name = "devbox-development";
  paths = [
    php81
  
    php81Extensions.blackfire
  ];
  pathsToLink = [ "/bin" "/share" "/lib"];
}
```

**Comment by loreto** [comment] 2022-12-16 14:07
Thanks for reporting, taking a look today. @mikeland86

**Comment by gcurtis** [comment] 2022-12-16 14:30
Thanks for the detailed report. Can you try updating the `nixpkgs.commit` in your `devbox.json` to `7a3f450e4af7c015a78d5d182499c8c6170418e5`?

```json
{
  "packages": [
    "php81",
    "php81Extensions.blackfire"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "52e3e80afff4b16ccb7c52e9f0f5220552f03d04"
  }
}
```

I think the problem is that this version of the package doesn't include an extension name by default. A newer version does though - see nixos/nixpkgs@152d32009174d62527dd36f8a1d472763a087586.

@mikeland86 do you know if we should be doing something like this?

```diff
-php81 = pkgs.php81.withExtensions ({ enabled, all }: enabled ++ (with all; [ blackfire ]));
+php81 = pkgs.php81.withExtensions ({ enabled, all }: enabled ++ (with all; [ (blackfire // { extensionName = "blackfire"; }) ]));
```

I'm not sure if this is a devbox problem or if this was just an issue with the package.

**Comment by calvinbaart** [comment] 2022-12-16 14:39
``7a3f450e4af7c015a78d5d182499c8c6170418e5`` works perfectly. I did get an error about the license being unfree but that is unrelated to this ticket.

**Comment by Lagoja** [comment] 2022-12-20 17:54
Closing this issue as resolved.

**Closed by Lagoja** 2022-12-20 17:54 UTC
