### ISSUE TITLE
[Bug]: Error installing Fleek

### ISSUE THREAD

**Issue by MaxwellDupre** [jetpack-io/devbox#1369] opened 2023-08-11 14:48 UTC
**Current Behavior (bug)**
Tried to install Fleek with
`>devbox global pull https://devbox.getfleek.dev/high`
I tried to google the problem but nothing found also I couldnt see any other issues related.

The output from this was:
dir.go:22: findProjectDir: path is 
dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox
dir.go:22: findProjectDir: path is 
dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox
[DEBUG] 2023/08/11 13:05:24 go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:51: Debug mode enabled.
[DEBUG] 2023/08/11 13:05:24 go.jetpack.io/devbox/internal/impl/dir.go:22: findProjectDir: path is /home/me/.local/share/devbox/global/default
? Global profile already exists. Overwrite? Yes
Info: Pulling global config from https://devbox.getfleek.dev/high
[DEBUG] 2023/08/11 13:05:27 go.jetpack.io/devbox/internal/impl/dir.go:22: findProjectDir: path is /home/me/.local/share/devbox/global/default
[DEBUG] 2023/08/11 13:05:28 go.jetpack.io/devbox/internal/plugin/plugin.go:100: Creating files for package "python3Full@latest" create files
Ensuring packages are installed.

Installing 24 packages: git@latest, htop@latest, gh@latest, glab@latest, fzf@latest, ripgrep@latest, vscode@latest, lazygit@latest, jq@latest, yq@latest, neovim@latest, neofetch@latest, btop@latest, cheat@latest, bash-preexec@latest, tree-sitter@latest, nodejs@latest, python3Full@latest, exa@latest, bat@latest, atuin@latest, zoxide@latest, direnv@latest, starship@latest.

[1/24] git@latest
[1/24] git@latest: Success
[2/24] htop@latest
[2/24] htop@latest: Success
[3/24] gh@latest
[3/24] gh@latest: Success
[4/24] glab@latest
[4/24] glab@latest: Success
[5/24] fzf@latest
[5/24] fzf@latest: Success
[6/24] ripgrep@latest
[6/24] ripgrep@latest: Success
[7/24] vscode@latest
[7/24] vscode@latest: Success
[8/24] lazygit@latest
error: getting status of '/nix/store/15ky94h9925chc77yv7fzxpq796kwr45-source/flake.nix': No such file or directory
[8/24] lazygit@latest: Fail
Error: error running "nix profile install": exit status 1

[DEBUG] 2023/08/11 13:05:43 go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:72: Command stderr: 
[DEBUG] 2023/08/11 13:05:43 go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:74: 
ExecutionID:3f616f2fdc12494c8929200abdd1b0d6
error running "nix profile install": exit status 1
go.jetpack.io/devbox/internal/nix/nixprofile.ProfileInstall
        go.jetpack.io/devbox/internal/nix/nixprofile/profile.go:240
go.jetpack.io/devbox/internal/impl.(*Devbox).addPackagesToProfile
        go.jetpack.io/devbox/internal/impl/packages.go:299
go.jetpack.io/devbox/internal/impl.(*Devbox).syncPackagesToProfile
        go.jetpack.io/devbox/internal/impl/packages.go:245
go.jetpack.io/devbox/internal/impl.(*Devbox).ensurePackagesAreInstalled
        go.jetpack.io/devbox/internal/impl/packages.go:207
go.jetpack.io/devbox/internal/impl.(*Devbox).PrintEnv
        go.jetpack.io/devbox/internal/impl/devbox.go:284
go.jetpack.io/devbox/internal/impl.(*Devbox).Install
        go.jetpack.io/devbox/internal/impl/devbox.go:263
go.jetpack.io/devbox/internal/boxcli.installCmdFunc
        go.jetpack.io/devbox/internal/boxcli/install.go:42
go.jetpack.io/devbox/internal/boxcli.pullCmdFunc
        go.jetpack.io/devbox/internal/boxcli/pull.go:84
go.jetpack.io/devbox/internal/boxcli.pullCmd.func1
        go.jetpack.io/devbox/internal/boxcli/pull.go:36
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.6.1/command.go:968
go.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute
        go.jetpack.io/devbox/internal/boxcli/midcobra/midcobra.go:58
go.jetpack.io/devbox/internal/boxcli.Execute
        go.jetpack.io/devbox/internal/boxcli/root.go:102
go.jetpack.io/devbox/internal/boxcli.Main
        go.jetpack.io/devbox/internal/boxcli/root.go:123
main.main
        go.jetpack.io/devbox/cmd/devbox/main.go:11
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
[DEBUG] 2023/08/11 13:05:43 go.jetpack.io/devbox/internal/impl/dir.go:22: findProjectDir: path is 
[DEBUG] 2023/08/11 13:05:43 go.jetpack.io/devbox/internal/impl/dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox

**Expected Behavior (fix)**
I expected the install to run without any problems as my system is not so unusual.

**Additional context**
Output of `devbox version -v`:
dir.go:22: findProjectDir: path is 
dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox
dir.go:22: findProjectDir: path is 
dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox
[DEBUG] 2023/08/11 15:41:51 go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:51: Debug mode enabled.
Version:     0.5.7
Platform:    linux_amd64
Commit:      none
Commit Time: unknown
Go Version:  go1.20.6
Launcher:    
[DEBUG] 2023/08/11 15:41:51 go.jetpack.io/devbox/internal/impl/dir.go:22: findProjectDir: path is 
[DEBUG] 2023/08/11 15:41:51 go.jetpack.io/devbox/internal/impl/dir.go:66: finding devbox.json in dir: /home/me/Documents/dvbox

My `devbox.json` file:
{
  "packages": [
    "python-full@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}

**Comment by bketelsen** [comment] 2023-08-15 00:04
the problem is `lazygit` in the nix store or index. I'm going to remove it from fleek to resolve this until it's fixed upstream.

**Comment by bketelsen** [comment] 2023-08-15 00:11
@mikeland73 you can close this as fixed externally.

**Closed** 2023-08-15 04:06 UTC
Labels: bug
